### ISSUE TITLE
vagrant warning (Could not retrieve fact fqdn)

### ISSUE THREAD

**Issue by magmabyte** [meet-here/vagrant-env#5]
This seems to have something to do with Puppet and the host name of the machine. What is the reason/are the consequences? Should we fix it?

**Comment by sknebel** [comment]
When did you get this? I can't reproduce it right now

**Comment by magmabyte** [comment]
This probably doesn't happen with the Ubuntu Puppet version that is the default option now. I got the warning for the previous Ubuntu version that doesn't work anymore anyways.
