### ISSUE TITLE
templatedir warning

### ISSUE THREAD

**Issue by magmabyte** [meet-here/vagrant-env#6]
```
==> meet_here: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> meet_here:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
```

when provisioning the current Ubuntu Puppet machine with vagrant up.

**Comment by sknebel** [comment]
Will be fixed in next vagrant update (and require a change of syntax in the vagrant file), upstream bug here:
https://github.com/mitchellh/vagrant/issues/3740

 If someone has this as an error (because they use puppet 4) already, there are workarounds available, also see the link

**Comment by sknebel** [comment]
paging @Bartzi
